# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 16:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permrule',
            name='platform',
            field=models.ManyToManyField(blank=True, to='cmdb.PlatformType'),
        ),
        migrations.AlterField(
            model_name='permrule',
            name='user_group',
            field=models.ManyToManyField(blank=True, to='users.UserGroup'),
        ),
        migrations.AlterField(
            model_name='permrule',
            name='username',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='comment',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
