# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180110_0023'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permrule',
            table='ops_perm_rule',
        ),
        migrations.AlterModelTable(
            name='user',
            table='ops_users',
        ),
        migrations.AlterModelTable(
            name='usergroup',
            table='ops_user_group',
        ),
    ]
