# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-18 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ansible_CallBack_Model_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u8f93\u51fa\u5185\u5bb9')),
            ],
            options={
                'db_table': 'ops_ansible_model_result',
                'verbose_name': 'Ansible\u6a21\u5757\u6267\u884c\u7ed3\u679c\u65e5\u5fd7',
                'verbose_name_plural': 'Ansible\u6a21\u5757\u6267\u884c\u7ed3\u679c\u65e5\u5fd7',
            },
        ),
        migrations.CreateModel(
            name='AnsibleModelRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansible_user', models.CharField(default=None, max_length=16, verbose_name='\u64cd\u4f5c\u7528\u6237')),
                ('ansible_host', models.TextField(blank=True, null=True, verbose_name='\u811a\u672c\u6267\u884c\u4e3b\u673a')),
                ('ansible_model', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u6a21\u5757\u540d\u79f0')),
                ('ansible_args', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='\u6a21\u5757\u53c2\u6570')),
                ('create_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6267\u884c\u65f6\u95f4')),
                ('end_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
            ],
            options={
                'db_table': 'ops_ansible_model_record',
                'verbose_name': 'Ansible\u6a21\u5757\u6267\u884c\u8bb0\u5f55\u8868',
                'verbose_name_plural': 'Ansible\u6a21\u5757\u6267\u884c\u8bb0\u5f55\u8868',
            },
        ),
        migrations.CreateModel(
            name='AnsibleScripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u811a\u672c\u540d\u79f0')),
                ('script_uuid', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u811a\u672cuuid')),
                ('exec_host', models.TextField(blank=True, null=True, verbose_name='\u811a\u672c\u6267\u884c\u4e3b\u673a')),
                ('script_file', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u811a\u672c\u6587\u4ef6')),
                ('script_arg', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u811a\u672c\u53c2\u6570')),
                ('exec_timeout', models.CharField(blank=True, max_length=4, null=True, verbose_name='\u811a\u672c\u6267\u884c\u8d85\u65f6\u65f6\u95f4')),
                ('creator', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u811a\u672c\u521b\u5efa\u8005')),
                ('create_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u811a\u672c\u521b\u5efa\u65f6\u95f4')),
                ('modifier', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u811a\u672c\u4fee\u6539\u8005')),
                ('modify_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u811a\u672c\u4fee\u6539\u65f6\u95f4')),
                ('debug_mode', models.CharField(default='off', max_length=4, verbose_name='\u811a\u672c\u8c03\u8bd5\u6a21\u5f0f')),
                ('state', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u811a\u672c\u72b6\u6001')),
            ],
            options={
                'db_table': 'ops_ansible_scripts',
                'verbose_name': 'ansible\u4f5c\u4e1a\u811a\u672c',
                'verbose_name_plural': 'ansible\u4f5c\u4e1a\u811a\u672c',
            },
        ),
        migrations.CreateModel(
            name='AnsibleTaskRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7a0b\u5e8f\u540d\u79f0')),
                ('ansible_group', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6267\u884c\u4e3b\u673a\u7ec4')),
                ('app_path', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7a0b\u5e8f\u8def\u5f84')),
                ('release_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u7a0b\u5e8f\u76ee\u6807\u66f4\u65b0\u8def\u5f84')),
                ('update_file_type', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u53d1\u5e03\u5305\u7c7b\u578b')),
                ('backup_path', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7a0b\u5e8f\u5907\u4efd\u8def\u5f84')),
                ('backup_file', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u7a0b\u5e8f\u5907\u4efd\u6587\u4ef6')),
                ('ansible_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u64cd\u4f5c\u7528\u6237')),
                ('frameworks', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u6846\u67b6\u7c7b\u578b')),
                ('create_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6267\u884c\u65f6\u95f4')),
            ],
            options={
                'db_table': 'ops_ansible_task_record',
                'verbose_name': 'Ansible\u4efb\u52a1\u6267\u884c\u8bb0\u5f55\u8868',
                'verbose_name_plural': 'Ansible\u4efb\u52a1\u6267\u884c\u8bb0\u5f55\u8868',
            },
        ),
        migrations.CreateModel(
            name='JobLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, max_length=64, null=True)),
                ('job_uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('app_type', models.CharField(blank=True, max_length=32, null=True)),
                ('start_time', models.CharField(blank=True, max_length=32, null=True)),
                ('end_time', models.CharField(blank=True, max_length=32, null=True)),
                ('runtime', models.CharField(blank=True, max_length=8, null=True)),
                ('state', models.CharField(blank=True, max_length=8, null=True)),
                ('excutor', models.CharField(blank=True, max_length=16, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ops_job_logs',
                'verbose_name': '\u4f5c\u4e1a\u6267\u884c\u5386\u53f2',
                'verbose_name_plural': '\u4f5c\u4e1a\u6267\u884c\u5386\u53f2',
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u53d1\u5e03\u6a21\u677f\u540d\u79f0')),
                ('app_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u53d1\u5e03\u7a0b\u5e8f\u540d\u79f0')),
                ('app_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u9879\u76ee\u7c7b\u578b')),
                ('frame_type', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u7a0b\u5e8f\u6846\u67b6')),
                ('release_type', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u53d1\u5e03\u65b9\u5f0f')),
                ('host_group', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u53d1\u5e03\u4e3b\u673a\u7ec4')),
                ('playbook', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u53d1\u5e03\u4efb\u52a1\u4fe1\u606f')),
                ('inventory', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u53d1\u5e03\u4e3b\u673a\u4fe1\u606f')),
                ('update_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6a21\u677f\u66f4\u65b0\u65f6\u95f4')),
                ('get_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u83b7\u53d6\u4ee3\u7801\u65b9\u5f0f')),
                ('code_path', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u4ee3\u7801\u5b58\u50a8\u8def\u5f84')),
                ('creator', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u6a21\u677f\u521b\u5efa\u8005')),
                ('state', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u6d41\u7a0b\u72b6\u6001')),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'ops_task_template',
                'verbose_name': '\u4efb\u52a1\u6a21\u677f',
                'verbose_name_plural': '\u4efb\u52a1\u6a21\u677f',
            },
        ),
        migrations.AddField(
            model_name='ansible_callback_model_result',
            name='log_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opstask.AnsibleModelRecord'),
        ),
    ]
