# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-28 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opstask', '3442_auto_20180714_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibletaskrecord',
            name='release_version',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u53d1\u884c\u7248\u672c'),
        ),
        migrations.AddField(
            model_name='joblogs',
            name='version_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
