# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-13 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opstask', '3444_auto_20181223_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleTaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.SmallIntegerField(verbose_name='\u5e94\u7528ID')),
                ('app_type', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u9879\u76ee\u7c7b\u578b')),
                ('app_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7a0b\u5e8f\u540d\u79f0')),
                ('app_version', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u7a0b\u5e8f\u7248\u672c')),
                ('creator', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4efb\u52a1\u521b\u5efa\u8005')),
                ('change_logs', models.TextField(blank=True, null=True, verbose_name='\u7a0b\u5e8f\u7248\u672c\u53d8\u66f4\u65e5\u5fd7')),
                ('release_type', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u53d1\u5e03\u7c7b\u578b')),
                ('get_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u83b7\u53d6\u4ee3\u7801\u65b9\u5f0f')),
                ('svn_path', models.CharField(blank=True, max_length=256, null=True, verbose_name='svn\u8def\u5f84')),
                ('dst_path', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u589e\u91cf\u53d1\u5e03\u5305\u8def\u5f84')),
                ('ansible_group', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6267\u884c\u4e3b\u673a\u7ec4')),
                ('reload_switch', models.CharField(blank=True, max_length=4, null=True, verbose_name='\u7a0b\u5e8f\u91cd\u542f\u5f00\u5173')),
                ('task_run_type', models.CharField(blank=True, max_length=8, null=True, verbose_name='ansible\u4efb\u52a1\u8fd0\u884c\u65b9\u5f0f')),
                ('task_status', models.SmallIntegerField(default=0, verbose_name='\u4efb\u52a1\u72b6\u6001')),
                ('create_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6267\u884c\u65f6\u95f4')),
            ],
            options={
                'db_table': 'ops_ansible_task_list',
                'verbose_name': 'Ansible\u4efb\u52a1\u8868',
                'verbose_name_plural': 'Ansible\u4efb\u52a1\u8868',
            },
        ),
    ]
