# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-05 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opstask', '3445_ansibletasklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibletasklist',
            name='hosts_list',
            field=models.TextField(blank=True, null=True, verbose_name='\u6267\u884c\u4e3b\u673a\u5217\u8868'),
        ),
        migrations.AddField(
            model_name='ansibletaskrecord',
            name='hosts_list',
            field=models.TextField(blank=True, null=True, verbose_name='\u6267\u884c\u4e3b\u673a\u5217\u8868'),
        ),
    ]
