# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=32, unique=True)),
                ('app_type', models.CharField(blank=True, max_length=32, null=True)),
                ('group_type', models.CharField(blank=True, max_length=16, null=True)),
                ('frameworks', models.CharField(blank=True, max_length=10, null=True)),
                ('comment', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'ansible_group',
                'verbose_name': 'ansible\u5206\u7ec4',
                'verbose_name_plural': 'ansible\u5206\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5e94\u7528\u540d\u79f0')),
                ('app_type', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u5e94\u7528\u7c7b\u578b')),
                ('frameworks', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u6846\u67b6\u7c7b\u578b')),
                ('main_path', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u90e8\u7f72\u8def\u5f84')),
                ('service_path', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u540e\u7aef\u90e8\u7f72\u8def\u5f84')),
                ('root_path', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u524d\u7aef\u90e8\u7f72\u8def\u5f84')),
                ('run_port', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u7a0b\u5e8f\u7aef\u53e3')),
                ('backup_path', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5907\u4efd\u8def\u5f84')),
                ('work_path', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5de5\u4f5c\u533a\u95f4')),
            ],
            options={
                'db_table': 'app_lists',
                'verbose_name': '\u7a0b\u5e8f\u5e94\u7528\u4fe1\u606f',
                'verbose_name_plural': '\u7a0b\u5e8f\u5e94\u7528\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='BackupLogs',
            fields=[
                ('backup_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(blank=True, max_length=32, null=True)),
                ('project', models.CharField(blank=True, max_length=32, null=True)),
                ('backup_file', models.CharField(blank=True, max_length=256, null=True)),
                ('create_date', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'backup_info',
                'verbose_name': '\u6587\u4ef6\u5907\u4efd\u4fe1\u606f',
                'verbose_name_plural': '\u6587\u4ef6\u5907\u4efd\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='PlatformType',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=16, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=16, null=True)),
                ('comment', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'platform_lists',
                'verbose_name': '\u9879\u76ee\u5206\u7c7b',
                'verbose_name_plural': '\u9879\u76ee\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('server_id', models.AutoField(primary_key=True, serialize=False)),
                ('private_ip', models.CharField(max_length=16, unique=True, verbose_name='\u79c1\u7f51\u5730\u5740')),
                ('resource_area', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6240\u5728\u533a\u57df')),
                ('hostname', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u4e3b\u673a\u540d\u79f0')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='SSH\u7528\u6237')),
                ('password', models.CharField(blank=True, max_length=64, null=True, verbose_name='SSH\u5bc6\u7801')),
                ('rsa_key', models.CharField(blank=True, max_length=64, null=True, verbose_name='SSH\u5bc6\u94a5')),
                ('host_port', models.IntegerField(blank=True, null=True, verbose_name='SSH\u7aef\u53e3')),
                ('ab_group', models.ManyToManyField(related_name='serverinfos', to='cmdb.AnsibleGroup', verbose_name='Ansible\u5206\u7ec4')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.PlatformType', verbose_name='\u9879\u76ee\u5e73\u53f0')),
            ],
            options={
                'db_table': 'server_lists',
                'verbose_name': '\u670d\u52a1\u5668\u4fe1\u606f',
                'verbose_name_plural': '\u670d\u52a1\u5668\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='appinfo',
            name='app_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.ServerInfo', verbose_name='\u5e94\u7528\u5730\u5740'),
        ),
    ]
