# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformtype',
            name='short_name',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
