# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20180110_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='create_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='create_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
