# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20180301_0140'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ansiblegroup',
            table='ops_hosts_group',
        ),
        migrations.AlterModelTable(
            name='appinfo',
            table='ops_apps',
        ),
        migrations.AlterModelTable(
            name='backuplogs',
            table='ops_backup_log',
        ),
        migrations.AlterModelTable(
            name='platformtype',
            table='ops_projects',
        ),
        migrations.AlterModelTable(
            name='serverinfo',
            table='ops_hosts',
        ),
    ]
