# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20180301_0354'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='platformtype',
            table='ops_platform',
        ),
    ]
