# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-13 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20180301_0410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ansiblegroup',
            options={'permissions': (('has_read_ansible_group', '\u8bfb\u53d6ansible\u7ec4\u6743\u9650'), ('has_change_ansible_group', '\u4fee\u6539ansible\u7ec4\u6743\u9650'), ('has_add_ansible_group', '\u6dfb\u52a0ansible\u7ec4\u6743\u9650'), ('has_delete_ansible_group', '\u5220\u9664ansible\u7ec4\u6743\u9650')), 'verbose_name': 'ansible\u5206\u7ec4', 'verbose_name_plural': 'ansible\u5206\u7ec4'},
        ),
        migrations.AlterModelOptions(
            name='appinfo',
            options={'permissions': (('has_read_app', '\u8bfb\u53d6\u5e94\u7528\u6743\u9650'), ('has_change_app', '\u4fee\u6539\u5e94\u7528\u6743\u9650'), ('has_add_app', '\u6dfb\u52a0\u5e94\u7528\u6743\u9650'), ('has_delete_app', '\u5220\u9664\u5e94\u7528\u6743\u9650')), 'verbose_name': '\u7a0b\u5e8f\u5e94\u7528\u4fe1\u606f', 'verbose_name_plural': '\u7a0b\u5e8f\u5e94\u7528\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='platformtype',
            options={'permissions': (('has_read_project', '\u8bfb\u53d6\u9879\u76ee\u6743\u9650'), ('has_change_project', '\u4fee\u6539\u9879\u76ee\u6743\u9650'), ('has_add_project', '\u6dfb\u52a0\u9879\u76ee\u6743\u9650'), ('has_delete_project', '\u5220\u9664\u9879\u76ee\u6743\u9650')), 'verbose_name': '\u9879\u76ee\u5206\u7c7b', 'verbose_name_plural': '\u9879\u76ee\u5206\u7c7b'},
        ),
        migrations.AlterModelOptions(
            name='serverinfo',
            options={'permissions': (('has_read_server', '\u8bfb\u53d6\u4e3b\u673a\u6743\u9650'), ('has_change_server', '\u4fee\u6539\u4e3b\u673a\u6743\u9650'), ('has_add_server', '\u6dfb\u52a0\u4e3b\u673a\u6743\u9650'), ('has_delete_server', '\u5220\u9664\u4e3b\u673a\u6743\u9650')), 'verbose_name': '\u670d\u52a1\u5668\u4fe1\u606f', 'verbose_name_plural': '\u670d\u52a1\u5668\u4fe1\u606f'},
        ),
    ]
