# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-15 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20180713_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='svn_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='SVN\u94fe\u63a5'),
        ),
    ]
