# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-08 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_appinfo_svn_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='app_alias',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='\u5e94\u7528\u522b\u540d'),
        ),
    ]
