# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-08 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_appinfo_app_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinfo',
            name='app_alias',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
    ]
