# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-09 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_auto_20180808_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansiblegroup',
            name='frameworks',
        ),
        migrations.RemoveField(
            model_name='ansiblegroup',
            name='group_type',
        ),
    ]
