# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-09 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0010_auto_20180809_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinfo',
            name='app_ip',
        ),
        migrations.AddField(
            model_name='appinfo',
            name='app_ip',
            field=models.ManyToManyField(related_name='app_server_ip', to='cmdb.ServerInfo', verbose_name='\u5e94\u7528\u5730\u5740'),
        ),
    ]
