# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-15 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_auto_20180809_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='app_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, '\u7981\u7528'), (1, '\u542f\u7528'), (2, '\u521d\u59cb\u5316'), (3, '\u53d1\u5e03\u4e2d'), (4, '\u53d1\u5e03\u5b8c\u6210')], null=True, verbose_name='\u5e94\u7528\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='root_path',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u79c1\u6709\u4e91root\u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='service_path',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u79c1\u6709\u4e91service\u8def\u5f84'),
        ),
    ]
