# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-05 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0012_auto_20180815_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='private_ip',
            field=models.CharField(max_length=16, verbose_name='\u79c1\u7f51\u5730\u5740'),
        ),
    ]
