# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-28 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendserver',
            name='weight',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='\u540e\u7aef\u4e3b\u673a\u6743\u91cd'),
        ),
    ]
