# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-13 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opsconfig', '0002_auto_20180528_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backendserver',
            options={'permissions': (('has_read_backendserver', '\u8bfb\u53d6BackendServer\u6743\u9650'), ('has_change_backendserver', '\u4fee\u6539BackendServer\u6743\u9650'), ('has_add_backendserver', '\u6dfb\u52a0BackendServer\u6743\u9650'), ('has_delete_backendserver', '\u5220\u9664BackendServer\u6743\u9650')), 'verbose_name': '\u8d1f\u8f7d\u5747\u8861\u540e\u7aef\u670d\u52a1\u5668', 'verbose_name_plural': '\u8d1f\u8f7d\u5747\u8861\u540e\u7aef\u670d\u52a1\u5668'},
        ),
        migrations.AlterModelOptions(
            name='serverloadbalancer',
            options={'permissions': (('has_read_slb', '\u8bfb\u53d6SLB\u6743\u9650'), ('has_change_slb', '\u4fee\u6539SLB\u6743\u9650'), ('has_add_slb', '\u6dfb\u52a0SLB\u6743\u9650'), ('has_delete_slb', '\u5220\u9664SLB\u6743\u9650')), 'verbose_name': '\u8d1f\u8f7d\u5747\u8861', 'verbose_name_plural': '\u8d1f\u8f7d\u5747\u8861'},
        ),
    ]
